### ISSUE TITLE
Bot crashes (Sentry)

### ISSUE THREAD

**Issue by ghost** [PokemonGoF/PokemonGo-Bot-Backup#16]
### Expected Behavior

For the bot to actually work. . .
### Actual Behavior

After the encrypt.dll file loads successfully, the bot crashes.
### Your FULL config.json (remove your username, password, gmapkey and any other private info)

```
{
    "auth_service": "google",
    "username": "",
    "password": "",
    "location": "52.39037297896968,4.828920364379883",
    "gmapkey": "",
    "tasks": [{
        "type": "HandleSoftBan",
        "$$hashKey": "object:21"
    }, {
        "type": "CollectLevelUpReward",
        "$$hashKey": "object:22"
    }, {
        "type": "IncubateEggs",
        "config": {
            "longer_eggs_first": true
        },
        "$$hashKey": "object:23"
    }, {
        "type": "TransferPokemon",
        "$$hashKey": "object:24"
    }, {
        "type": "EvolveAll",
        "config": {
            "evolve_all": "all",
            "first_evolve_by": "iv",
            "evolve_above_cp": 100,
            "evolve_above_iv": 0.7,
            "logic": "and",
            "evolve_speed": 20,
            "use_lucky_egg": false
        },
        "$$hashKey": "object:25"
    }, {
        "type": "RecycleItems",
        "config": {
            "item_filter": {
                "Pokeball": {
                    "keep": 100
                },
                "Potion": {
                    "keep": 10
                },
                "Super Potion": {
                    "keep": 20
                },
                "Hyper Potion": {
                    "keep": 30
                },
                "Revive": {
                    "keep": 30
                },
                "Razz Berry": {
                    "keep": 100
                }
            }
        },
        "$$hashKey": "object:26"
    }, {
        "type": "CatchVisiblePokemon",
        "$$hashKey": "object:27"
    }, {
        "type": "CatchLuredPokemon",
        "$$hashKey": "object:28"
    }, {
        "type": "SpinFort",
        "$$hashKey": "object:29"
    }, {
        "type": "MoveToFort",
        "config": {
            "lure_attraction": true,
            "lure_max_distance": 2000
        },
        "$$hashKey": "object:30"

    }],
    "map_object_cache_time": 5,
    "forts": {
        "avoid_circles": true,
        "max_circle_size": 50
    },
    "websocket_server": false,
    "walk": "25",
    "action_wait_min": 1,
    "action_wait_max": 4,
    "debug": false,
    "test": false,
    "health_record": true,
    "location_cache": true,
    "distance_unit": "mi",
    "reconnecting_timeout": 15,
    "evolve_captured": "NONE",
    "catch_randomize_reticle_factor": 1,
    "catch_randomize_spin_factor": 1,
    "catch": {
        "any": {
            "catch_above_cp": 0,
            "catch_above_iv": 0,
            "logic": "or"
        }
    },
    "release": {
        "any": {
            "release_below_cp": 0,
            "release_below_iv": 0,
            "logic": "or"
        }
    },
    "vips": {
        "Any pokemon put here directly force to use Berry & Best Ball to capture, to secure the capture rate!": {},
        "any": {
            "catch_above_cp": 1200,
            "catch_above_iv": 0.9,
            "logic": "or"
        },
        "Lapras": {},
        "Moltres": {},
        "Zapdos": {},
        "Articuno": {},
        "// S-Tier pokemons (if pokemon can be evolved into tier, list the representative)": {},
        "Mewtwo": {},
        "Dragonite": {},
        "Snorlax": {},
        "// Mew evolves to Mewtwo": {},
        "Mew": {},
        "Arcanine": {},
        "Vaporeon": {},
        "Gyarados": {},
        "Exeggutor": {},
        "Muk": {},
        "Weezing": {},
        "Flareon": {}
    }
}
```
### Output when issue occurred

```
2016-09-14 10:18:26,634 [PokemonGoBot] [INFO]
Traceback (most recent call last):
  File "pokecli.py", line 802, in <module>
    main()
  File "pokecli.py", line 238, in main
    report_summary(bot)
  File "pokecli.py", line 286, in report_summary
    metrics.capture_stats()
  File "C:\Test\PokemonGo-Bot\pokemongo_bot\metrics.py", line 105, in capture_stats
    self.dust['latest'] = self.bot.stardust
  File "C:\Test\PokemonGo-Bot\pokemongo_bot\__init__.py", line 72, in stardust
    return filter(lambda y: y['name'] == 'STARDUST', self._player['currencies'])[0]['amount']
AttributeError: 'PokemonGoBot' object has no attribute '_player'
2016-09-14 10:18:27,490 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\raven\transport\threaded.py", line 174, in send_sync
    super(ThreadedHTTPTransport, self).send(data, headers)
  File "C:\Python27\lib\site-packages\raven\transport\http.py", line 47, in send
    ca_certs=self.ca_certs,
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 66, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 494, in open
    response = self._open(req, data)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 512, in _open
    '_open', req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 466, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\site-packages\raven\utils\http.py", line 46, in https_open
    return self.do_open(ValidHTTPSConnection, req)
  File "C:\Python27\lib\site-packages\future\backports\urllib\request.py", line 1284, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "C:\Python27\lib\httplib.py", line 1057, in request
    self._send_request(method, url, body, headers)
  File "C:\Python27\lib\httplib.py", line 1097, in _send_request
    self.endheaders(body)
  File "C:\Python27\lib\httplib.py", line 1053, in endheaders
    self._send_output(message_body)
  File "C:\Python27\lib\httplib.py", line 895, in _send_output
    msg += message_body
  File "C:\Python27\lib\encodings\utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte
2016-09-14 10:18:27,831 [sentry.errors.uncaught] [ERROR] [u"AttributeError: 'PokemonGoBot' object has no attribute '_player'", u'  File "pokecli.py", line 802, in <module>', u'  File "pokecli.py", line 238, in main', u'  File "pokecli.py", line 286, in report_summary', u'  File "C:\\Test\\PokemonGo-Bot\\pokemongo_bot\\metrics.py", line 105, in capture_stats', u'  File "C:\\Test\\PokemonGo-Bot\\pokemongo_bot\\__init__.py", line 72, in stardust']
Sentry is attempting to send 1 pending error messages
Waiting up to 10 seconds
```
### Steps to Reproduce

Just restarting the bot.
### Other Information

OS: Windows 10

 

Branch:

 

Git Commit: unknown

 

Python Version: 3.5

**Comment by ukos-git** [comment]
Now I'm getting the message too.
The `0x9c` char seems not the problem. I got error messages regarding that char previously a lot. Don't know if/why it matters.
The core problem seems to be something else related to the SSL verification. Maybe something due to the changed github repo and then the sentry-authentification changed ... - just a guess.
Hard to read the error. 
`2016-09-14 10:18:27,490 [sentry.errors] [ERROR] Sentry responded with an error: 'utf8' codec can't decode byte 0x9c in position 1: invalid start byte (url: https://app.getsentry.com/api/90254/store/)` 
is the sentry error I guess.
The sentry error in your entry on the web page btw is
`{"error":"Unable to find authentication information"}`

Right before that error the actual error is stated:
`AttributeError: 'PokemonGoBot' object has no attribute '_player'`

**Comment by ghost** [comment]
I thought the issue with stardust was fixed in dev a couple days ago. It's #5254
